engineStrict: true
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
overrides:
  esbuild@>=0.17.0 <0.28.1: ^0.28.1
  postcss@<8.5.10: ^8.5.10
minimumReleaseAgeExclude:
  - postcss@8.5.10
  - esbuild@0.28.1
